version: "3.8"

services:
  z74pg:
    image: zabbix/zabbix-server-pgsql:7.4.2-alpine
    container_name: z74pg
    environment:
      DB_SERVER_HOST: pg16.ext
      DB_SERVER_PORT: '7416'
      POSTGRES_DB: z74
      POSTGRES_PASSWORD: zabbix
      POSTGRES_USER: zabbix
      TZ: Europe/Riga
      ZBX_ALLOWUNSUPPORTEDDBVERSIONS: '1'
      ZBX_CACHESIZE: 256M
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTALERTERS: '1'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '1'
      ZBX_STARTHTTPAGENTPOLLERS: '0'
      ZBX_STARTHTTPPOLLERS: '0'
      ZBX_STARTLLDPROCESSORS: '1'

      ZBX_STARTPOLLERS: '0'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '0'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTPROXYPOLLERS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
        #      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

      ZBX_STARTPINGERS: '0'

    ports:
      - "17451:10051"
    networks:
      podnet:
        ipv4_address: 10.88.2.74
    tty: true
    restart: unless-stopped


  z74prx.do:
    image: zabbix/zabbix-proxy-sqlite3:7.4.2-alpine
    container_name: z74prx.do
    environment:
      ZBX_PROXYMODE: '1'
      TZ: Europe/Riga
      ZBX_CACHESIZE: 256M
      ZBX_SERVER_HOST: 10.88.2.74
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '0'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '0'
      ZBX_STARTHTTPAGENTPOLLERS: '0'
      ZBX_STARTHTTPPOLLERS: '0'

      ZBX_STARTPINGERS: '0'


      ZBX_STARTPOLLERS: '0'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '0'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "27451:10051"
    networks:
      podnet:
        ipv4_address: 10.88.7.74
    tty: true
    restart: unless-stopped


networks:
  podnet:
    name: podman
    external: true

