version: "3.8"

services:
  browser:
    image: selenium/standalone-chrome:latest
    container_name: browser

    ports:
      - "4444:4444"
      - "7900:7900"

    networks:
      podnet:
        ipv4_address: 10.88.44.44

    tty: true

    restart: unless-stopped

    shm_size: "2g"

networks:
  podnet:
    name: podman
    external: true

