version: "3.8"

services:

  https.do:
    image: zabbix/zabbix-proxy-mysql:7.0.13-alpine
    container_name: https.do
    environment:
      DB_SERVER_HOST: 10.88.10.4
      DB_SERVER_PORT: 3306
      MYSQL_USER: 'z70prx'
      MYSQL_PASSWORD: 'zabbix'
      MYSQL_DATABASE: 'z70prx'
      ZBX_HOSTNAME: 'https'
      ZBX_CACHESIZE: '256M'
      ZBX_MAXCONCURRENTCHECKSPERPOLLER: '1'
      ZBX_ALLOWUNSUPPORTEDDBVERSIONS: '1'
      ZBX_PROXYMODE: '1'
      ZBX_PROXYOFFLINEBUFFER: '100'
      ZBX_ENABLEREMOTECOMMANDS: '1'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STARTPOLLERS: '1'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTPINGERS: '0'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTDISCOVERERS: '1'
      ZBX_STATSALLOWEDIP: 'second.ext'
      TZ: 'Europe/Riga'
      ZBX_SERVER_HOST: 'zs.ext'

    ports:
      - "27051:10051"
    networks:
      podnet:
        ipv4_address: 10.88.7.170
    tty: true
    restart: unless-stopped


networks:
  podnet:
    name: podman
    external: true

