version: "3.8"

services:

  https.do:
    image: zabbix/zabbix-proxy-sqlite3:7.0.13-alpine
    container_name: https.do
    environment:
      ZBX_PROXYMODE: '1'
      TZ: Europe/Riga
      ZBX_CACHESIZE: 256M
      ZBX_SERVER_HOST: 10.88.70.70
      ZBX_STARTAGENTPOLLERS: '0'
      ZBX_STARTBROWSERPOLLERS: '0'
      ZBX_STARTDBSYNCERS: '1'
      ZBX_STARTDISCOVERERS: '0'
      ZBX_STARTODBCPOLLERS: '0'
      ZBX_STARTIPMIPOLLERS: '0'
      ZBX_STARTHISTORYPOLLERS: '0'
      ZBX_STARTHTTPAGENTPOLLERS: '0'
      ZBX_STARTHTTPPOLLERS: '0'

      ZBX_STARTPINGERS: '0'


      ZBX_STARTPOLLERS: '0'
      ZBX_STARTJAVAPOLLERS: '0'
      ZBX_STARTPOLLERSUNREACHABLE: '0'

      ZBX_STARTPREPROCESSORS: '1'
      ZBX_STARTSNMPPOLLERS: '0'
      ZBX_STARTTRAPPERS: '2'
      ZBX_STATSALLOWEDIP: second.ext

    ports:
      - "27051:10051"
    networks:
      podnet:
        ipv4_address: 10.88.170.170
    tty: true
    restart: unless-stopped


networks:
  podnet:
    name: podman
    external: true

