version: "3.8"

services:
  mdb105:
    image: mariadb:10.5.26
    container_name: mdb105

    environment:
      MYSQL_ROOT_PASSWORD: 'zabbix'

    ports:
      - "1105:3306"

    volumes:
      - /root/podman/mariadb.conf.d/10.5.26:/etc/mysql/conf.d
      - /root/mariadb/datadir/10.5:/var/lib/mysql:Z

    networks:
      podnet:
        ipv4_address: 10.88.10.5

    tty: true

    restart: unless-stopped


networks:
  podnet:
    name: podman
    external: true

